# Estágio 1: Obter o código do GitHub
FROM alpine/git as clone
WORKDIR /app
RUN git clone https://github.com/PinangeMoratto/image-of-the-day.git

# Estágio 2: Construir a aplicação
FROM maven as construction
WORKDIR /app
COPY --from=clone /app/image-of-the-day /app
RUN mvn package

# Estágio 3: Disponibilizar a aplicação
FROM maven
WORKDIR /app
COPY --from=construction /app /app
EXPOSE 80
CMD ["java", "-jar", "app.jar"]
