FROM alpine/git as clone
WORKDIR /app
RUN git clone https://github.com/PinangeMoratto/image-of-the-day.git

FROM maven AS builder
WORKDIR /usr/src/iotd
COPY --from=clone /app/image-of-the-day /usr/src/iotd
RUN mvn -B dependency:go-offline
COPY . .
RUN mvn package

FROM openjdk
WORKDIR /app
COPY --from=builder /usr/src/iotd/target/iotd-service-0.1.0.jar .
EXPOSE 80
ENTRYPOINT ["java", "-jar", "/app/iotd-service-0.1.0.jar"]