# Estágio 1: Obter o código do GitHub
FROM alpine/git as clone
WORKDIR /app
RUN git clone https://github.com/PinangeMoratto/image-of-the-day.git

# Estágio 2: Construir a aplicação
FROM maven as construction
WORKDIR /app
COPY --from=clone /app/image-of-the-day .
RUN mvn -B dependency:go-offline
COPY . .
RUN mvn package

# Estágio 3: Disponibilizar a aplicação
FROM maven
WORKDIR /app
COPY --from=construction /app/image-of-the-day/target/iotd-service-0.1.0.jar .
EXPOSE 80
ENTRYPOINT ["java", "-jar", "/app/iotd-service-0.1.0.jar"]
